apiVersion: v1
kind: Service
metadata:
  name: apache-exporter-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 9117
      targetPort: 9117
      nodePort: 31524

