---
- name: Configuración de Prometheus
  become: true
  become_method: sudo
  hosts: localhost

  tasks:
  - name: Crear usuario prometheus
    user:
      name: prometheus
      shell: /bin/false
      createhome: no

  - name: Crear directorios de prometheus
    file:
      path: "{{ item }}"
      state: directory
      owner: prometheus
      group: prometheus
    with_items:
      - /etc/prometheus
      - /var/lib/prometheus

  - name: Descargar Prometheus
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
      dest: /tmp/prometheus-2.43.0.linux-amd64.tar.gz

  - name: Extraer Prometheus
    unarchive:
      src: /tmp/prometheus-2.43.0.linux-amd64.tar.gz
      dest: /tmp/
      remote_src: yes
      creates: /tmp/prometheus-2.43.0.linux-amd64

  - name: Copiar prometheus a /usr/local/bin
    synchronize:
      src: /tmp/prometheus-2.43.0.linux-amd64/prometheus
      dest: /usr/local/bin/
#      owner: prometheus
#      group: prometheus

  - name: Copiar promtool a /usr/local/bin
    synchronize:
      src: /tmp/prometheus-2.43.0.linux-amd64/promtool
      dest: /usr/local/bin/
#      owner: prometheus
#      group: prometheus

  - name: Copiar archivo de consolas de prometheus
    synchronize:
      src: /tmp/prometheus-2.43.0.linux-amd64/consoles/
      dest: /etc/prometheus/consoles/
#      owner: prometheus
#      group: prometheus

  - name: Copiar librerias de consola de prometheus
    synchronize:
      src: /tmp/prometheus-2.43.0.linux-amd64/console_libraries/
      dest: /etc/prometheus/console_libraries/
#      owner: prometheus
#      group: prometheus

  - name: Eliminar archivos temporales
    file:
      path: "/tmp/prometheus-2.43.0.linux-amd64*"
      state: absent

  - name: Copiar archivo de configuración
    copy:
      src: /home/jesus-proyecto/prometheus.yml
      dest: /etc/prometheus/
      owner: prometheus
      group: prometheus

  - name: Crear archivo de servicio systemd
    copy:
      dest: /etc/systemd/system/prometheus.service
      content: |
        [Unit]
        Description=Prometheus
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=prometheus
        Group=prometheus
        Type=simple
        ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries

        [Install]
        WantedBy=multi-user.target

  - name: Recargar systemd
    systemd:
      daemon_reload: yes

  - name: Iniciar servicio Prometheus
    systemd:
      name: prometheus
      state: started
      enabled: yes
      
      
  - name: Crear usuario node_exporter
    user:
      name: node_exporter
      shell: /bin/false
      createhome: no
    become: yes      

  - name: Descargar y extraer node_exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
      dest: /tmp/node_exporter.tar.gz
    become: yes

  - name: Descomprimir node_exporter
    unarchive:
      src: /tmp/node_exporter.tar.gz
      dest: /opt
      remote_src: yes
    become: yes

  - name: Copiar node_exporter a /usr/local/bin
    synchronize:
      src: /opt/node_exporter-1.5.0.linux-amd64/node_exporter
      dest: /usr/local/bin/
#        owner: node_exporter
#        group: node_exporter
    become: yes

  - name: Establecer permisos en /usr/local/bin/node_exporter
    file:
      path: /usr/local/bin/node_exporter
      owner: node_exporter
      group: node_exporter
      mode: '0755'
    become: yes

  - name: Borrar archivos temporales de node_exporter
    file:
      path: /tmp/node_exporter.tar.gz
      state: absent
    become: yes

  - name: Crear archivo de servicio de node_exporter
    copy:
      content: |
        [Unit]
        Description=Node Exporter
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=node_exporter
        Group=node_exporter
        Type=simple
        ExecStart=/usr/local/bin/node_exporter

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/node_exporter.service
    become: yes

  - name: Arrancar y habilitar node_exporter
    service:
      name: node_exporter
      state: started
      enabled: yes

  - name: Configurar archivo de prometheus
    synchronize:
      src: /home/jesus-proyecto/prometheus.yml
      dest: /etc/prometheus/prometheus.yml
