apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter-service
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: mysql
  ports:
    - name: exporter
      protocol: TCP
      port: 9104
      targetPort: 9104
      nodePort: 31202
