{
 "title": "Apache",
 "description": "Apache Prometheus Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(apache_up, instance)"
   },
   {
    "name": "port",
    "query": "label_values(apache_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Peticiones totales",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peticiones Exporters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_gc_duration_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{instance=~\"$host:$port\"}"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "graph",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(apache_up{instance=~\"$host:$port\"} == 0)",
     "legendFormat": "Apache Up"
    },
    {
     "expr": "scalar(count(apache_up{instance=~\"$host:$port\"} == 1))",
     "legendFormat": "Apache Down"
    }
   ]
  },
  {
   "title": "Scrapeo fallido apache-exporter",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_exporter_scrape_failures_total",
     "legendFormat": "Kilobytes Sent"
    },
    { "expr": "mysql_exporter_scrapes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current total apache accesses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apache_accesses_total{instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Accesses"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_scoreboard{instance=~\"$host:$port\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_workers{instance=~\"$host:$port\"}\n",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_cpuload{instance=~\"$host:$port\"}",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}